### ISSUE TITLE
CoreVideo: CVPixelBufferBacking leak 

### ISSUE THREAD

**Issue by Timstarockz** [gorastudio/SCNRecorder#5] opened 2019-06-26 23:04 UTC
Hi again! I seemed to have found a leak. I think it takes place in the same place as my other ticket #4 

Here is the leak I get back from Instruments:

`15	0x2a33c4000	VM: IOSurface	00:38.873.640	•	7.98 MiB	CoreVideo	CVPixelBufferBacking::performStandardMemoryLayoutAndCopyIOSurfaceCreationProperties(void*, unsigned char, __CFAllocator const*, __CFDictionary const*, __CFDictionary const*, __CFDictionary const*, __CFDictionary const*, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, void**, unsigned long*, unsigned long*, unsigned long*, unsigned long*, unsigned long*, __IOSurface**, void**, __CFDictionary const**)`

and

`165	0x159098000	VM: IOSurface	00:37.507.010	•	1.31 MiB	CoreImage	CreateCachedSurface`

the stack trace:
https://imgur.com/a/O9vJaLt

Both of these seem to be continuously spawning during recording. I'll keep doing some digging to see if I can find any root issues and more info. The one thing I'm not sure of is if it directly correlates with #4

**Comment by v-grigoriev** [comment] 2020-01-03 23:14
Should be fixed in the new version. I can't reproduce it and there are no memory leaks.

**Closed by v-grigoriev** 2020-01-03 23:14 UTC
