### ISSUE TITLE
Bad access when producing a pixel buffer

### ISSUE THREAD

**Issue by Timstarockz** [gorastudio/SCNRecorder#4] opened 2019-06-21 00:58 UTC
Hi! So I've run into an interesting issue that I found in InternalRecorder.swift. I managed to get it to crash at this line:

https://github.com/gorastudio/SCNRecorder/blob/6ea497e347cab67460a1fcc4a4a739d5d6a79a70/Source/InternalRecorder/InternalRecorder.swift#L278

I can never capture the frame with the actual error but I was able to see it output some sort of EXC_BAD_ACCESS error. This seems to only be happening to me when recording an SCNView.

**Comment by v-grigoriev** [comment] 2019-06-21 14:27
Hi! Yea, it looks interesting. Do you use Metal or OpenGL based rendering?

**Comment by Timstarockz** [comment] 2019-06-21 15:27
I currently use Metal based rendering. Mostly just out of the box SceneKit right now.

**Comment by v-grigoriev** [comment] 2019-06-21 15:29
OK, thank you! I will investigate for a week and get back to you.

**Comment by v-grigoriev** [comment] 2020-01-03 23:14
Should be fixed in the new version. I can't reproduce it and there are no memory leaks.

**Closed by v-grigoriev** 2020-01-03 23:14 UTC
Labels: bug
